### ISSUE TITLE
Docker fails: `block in materialize': Could not find minitest-5.14.2 in any of the sources (Bundler::GemNotFound)

### ISSUE THREAD

**Issue by agude** [MiniFate/MiniFate#39]
I get the following error on both Mac and Linux right now:

```
$ make refresh
....
$ make
rm -rf /tmp/jekyll-docker
mkdir -p /tmp/jekyll-docker
cp Gemfile /tmp/jekyll-docker
docker build /tmp/jekyll-docker -f Dockerfile -t jekyll-image
[+] Building 1.5s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                       0.0s
 => => transferring dockerfile: 37B                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                                                                                            1.4s
 => [1/4] FROM docker.io/library/ubuntu:20.04@sha256:c95a8e48bf88e9849f3e0f723d9f49fa12c5a00cfc6e60d2bc99d87555295e4c                                                                                      0.0s
 => [internal] load build context                                                                                                                                                                          0.0s
 => => transferring context: 107B                                                                                                                                                                          0.0s
 => CACHED [2/4] RUN apt-get -y update     && apt-get install -y         build-essential         git         ruby         ruby-dev         zlib1g-dev                                                      0.0s
 => CACHED [3/4] ADD Gemfile .                                                                                                                                                                             0.0s
 => CACHED [4/4] RUN gem install bundler     && gem update --system     && bundle install                                                                                                                  0.0s
 => exporting to image                                                                                                                                                                                     0.0s
 => => exporting layers                                                                                                                                                                                    0.0s
 => => writing image sha256:80c36d2215a768bf478764c90d5e173b274b82b379e802acd8aa996c7ffbf90f                                                                                                               0.0s
 => => naming to docker.io/library/jekyll-image                                                                                                                                                            0.0s
docker run --rm -p 4000:4000 -v /Users/agude/Project/MiniFate:/workspace -w /workspace jekyll-image bundle exec jekyll serve
/var/lib/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find minitest-5.14.2 in any of the sources (Bundler::GemNotFound)
	from /var/lib/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/spec_set.rb:81:in `map!'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/spec_set.rb:81:in `materialize'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/definition.rb:175:in `specs'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/definition.rb:245:in `specs_for'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/definition.rb:227:in `requested_specs'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/runtime.rb:91:in `block in definition_method'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/runtime.rb:20:in `setup'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.4/lib/bundler.rb:149:in `setup'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/setup.rb:20:in `block in <top (required)>'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/ui/shell.rb:136:in `with_level'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/ui/shell.rb:88:in `silence'
	from /var/lib/gems/2.7.0/gems/bundler-2.2.4/lib/bundler/setup.rb:20:in `<top (required)>'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
make: *** [serve] Error 1
exit: 2
```

**Comment by agude** [comment]
Here are errors during the `Step 9/10 : RUN gem install bundler     && gem update --system     && bundle install` step:

```
Installing RubyGems 3.2.4
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:50:in `<class:Specification>': undefined method `rubyforge_project=' for class `Gem::Specification' (NameError)
	from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:49:in `<top (required)>'
	from /var/lib/gems/2.7.0/gems/rubygems-update-3.2.4/lib/rubygems.rb:1348:in `require'
	from /var/lib/gems/2.7.0/gems/rubygems-update-3.2.4/lib/rubygems.rb:1348:in `<top (required)>'
	from setup.rb:23:in `require'
	from setup.rb:23:in `<main>'
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
```

And

```
Installing ffi 1.14.2 with native extensions

Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::UnknownHostError no such name (https://rubygems.org/gems/faraday-net_http-1.0.0.gem)
Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::UnknownHostError no such name (https://rubygems.org/gems/multipart-post-2.1.1.gem)


Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::UnknownHostError no such name (https://rubygems.org/gems/ruby2_keywords-0.0.2.gem)
Installing faraday-net_http 1.0.0
```
I suspect there is some network error? I don't think it's the same gems that show up in the error every time.

**Comment by agude** [comment]
When I open `bash` in the container and try to run I get this:

```
root@1ee14180a4ca:/workspace# bundle exec jekyll serve
Could not find minitest-5.14.2 in any of the sources
Run `bundle install` to install missing gems.
```

Then:

```
root@1ee14180a4ca:/workspace# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Fetching gem metadata from https://rubygems.org/.........
Using concurrent-ruby 1.1.7
Using thread_safe 0.3.6
Using zeitwerk 2.4.2
Using public_suffix 3.1.1
Using bundler 2.2.4
Using coffee-script-source 1.11.1
Using execjs 2.7.0
Using colorator 1.1.0
Using unf_ext 0.0.7.7
Using eventmachine 1.2.7
Using http_parser.rb 0.6.0
Using ffi 1.14.2
Using faraday-net_http 1.0.0
Using multipart-post 2.1.1
Using ruby2_keywords 0.0.2
Using forwardable-extended 2.6.0
Using gemoji 3.0.1
Using rb-fsevent 0.10.4
Using rexml 3.2.4
Using liquid 4.0.3
Using mercenary 0.3.6
Fetching minitest 5.14.2
Using rouge 3.23.0
Using safe_yaml 1.0.5
Fetching mini_portile2 2.4.0
Installing mini_portile2 2.4.0
Installing minitest 5.14.2
Using jekyll-paginate 1.1.0
Using rubyzip 2.3.0
Using jekyll-swiss 1.0.0
Using unicode-display_width 1.7.0
Using i18n 0.9.5
Using tzinfo 1.2.9
Using addressable 2.7.0
Using coffee-script 2.4.1
Using unf 0.1.4
Using em-websocket 0.5.2
Using ethon 0.12.0
Using faraday 1.3.0
Using rb-inotify 0.10.1
Using kramdown 2.3.0
Using pathutil 0.16.2
Fetching nokogiri 1.10.10
Using terminal-table 1.8.0
Using ruby-enum 0.8.0
Using jekyll-coffeescript 1.1.1
Using simpleidn 0.1.1
Using typhoeus 1.4.0
Using sawyer 0.8.2
Using sass-listen 4.0.0
Using listen 3.4.0
Using kramdown-parser-gfm 1.1.0
Using activesupport 6.0.3.4
Using commonmarker 0.17.13
Using dnsruby 1.61.5
Using octokit 4.20.0
Using sass 3.7.4
Using jekyll-watch 2.2.1
Using github-pages-health-check 1.16.1
Using jekyll-gist 1.5.0
Using jekyll-sass-converter 1.5.2
Using jekyll 3.9.0
Using jekyll-avatar 0.7.0
Using jekyll-commonmark 1.3.1
Using jekyll-default-layout 0.1.4
Using jekyll-feed 0.15.1
Using jekyll-github-metadata 2.13.0
Using jekyll-optional-front-matter 0.3.2
Using jekyll-readme-index 0.3.0
Using jekyll-redirect-from 0.16.0
Using jekyll-relative-links 0.6.1
Using jekyll-remote-theme 0.4.2
Using jekyll-seo-tag 2.6.1
Using jekyll-sitemap 1.4.0
Using jekyll-titles-from-headings 0.5.3
Using jekyll-commonmark-ghpages 0.1.6
Using jekyll-theme-architect 0.1.1
Using jekyll-theme-cayman 0.1.1
Using jekyll-theme-dinky 0.1.1
Using jekyll-theme-hacker 0.1.2
Using jekyll-theme-leap-day 0.1.1
Using jekyll-theme-merlot 0.1.1
Using jekyll-theme-midnight 0.1.1
Using jekyll-theme-minimal 0.1.1
Using jekyll-theme-modernist 0.1.1
Using jekyll-theme-primer 0.5.4
Using jekyll-theme-slate 0.1.1
Using jekyll-theme-tactile 0.1.1
Using jekyll-theme-time-machine 0.1.1
Using minima 2.5.1
Installing nokogiri 1.10.10 with native extensions
Using html-pipeline 2.14.0
Using jekyll-mentions 1.6.0
Using jemoji 0.12.0
Using github-pages 209
Bundle complete! 1 Gemfile dependency, 92 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Then:

```
root@1ee14180a4ca:/workspace# bundle exec jekyll serve
Configuration file: /workspace/_config.yml
            Source: /workspace
       Destination: /workspace/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
                    done in 0.295 seconds.
/var/lib/gems/2.7.0/gems/pathutil-0.16.2/lib/pathutil.rb:502: warning: Using the last argument as keyword parameters is deprecated
 Auto-regeneration: enabled for '/workspace'
    Server address: http://0.0.0.0:4000/
  Server running... press ctrl-c to stop.
```

So it **works** after the `bundle update`. 🤷

**Comment by agude** [comment]
It's still broken on my Linux box. 🤷 Same exact error.

**Comment by agude** [comment]
I was able to fix the containers by going into them, manually running `bundle update`, and then shutting them down. 🤷

I don't know why that didn't work in the `Dockerfile`.

**Comment by agude** [comment]
#81 seems to have fixed this.
